"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/Redux/Provider";
import NavBar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  const path = usePathname();
  const exceptionPath = ["/panel", "/login"];

  const [styleDisplay, setDisplayPlay] = useState(() => {
    return exceptionPath.some((exception) => path.includes(exception))
      ? "none"
      : null;
  });

  const checkPath = () => {
    if (exceptionPath.some((exception) => path.includes(exception))) {
      setDisplayPlay("none");
    }
  };

  useEffect(() => {
    checkPath();
  }, [path]);

  return (
    <html lang="en" className={inter.className}>
      <head>
        <script>
          {`
            function initMap() {}
          `}
        </script>
        <script
          defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB6Oe_agZZWDZb_qVe0yMMdtZowP2TKe5s&&libraries=geometry,places&callback=initMap"
        ></script>
      </head>
      <body>
        <div className="contRoot">
          <Providers>
            <NavBar display={styleDisplay} />
            {children}
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
