export const Provincias = [
  "Ciudad Autónoma de Buenos Aires",
  "Buenos Aires - GBA Norte",
  "Buenos Aires - GBA Sur",
  "Buenos Aires - GBA Oeste",
  "Buenos Aires - Costa Atlantica",
  "Buenos Aires",
  "Córdoba",
  "Santa Fe",
  "Mendoza",
  "Tucumán",
  "Entre Ríos",
  "Salta",
  "Misiones",
  "Chaco",
  "Corrientes",
  "Santiago del Estero",
  "San Juan",
  "Jujuy",
  "Río Negro",
  "Neuquén",
  "Formosa",
  "Chubut",
  "San Luis",
  "Catamarca",
  "La Rioja",
  "La Pampa",
  "Santa Cruz",
  "Tierra del Fuego",
];

export const ArrProvincias = [
  { name: "Ciudad Autónoma de Buenos Aires" },
  { name: "Buenos Aires - GBA Norte" },
  { name: "Buenos Aires - GBA Sur" },
  { name: "Buenos Aires - GBA Oeste" },
  { name: "Buenos Aires - Costa Atlantica" },
  { name: "Buenos Aires" },
  { name: "Córdoba" },
  { name: "Santa Fe" },
  { name: "Mendoza" },
  { name: "Tucumán" },
  { name: "Entre Ríos" },
  { name: "Salta" },
  { name: "Misiones" },
  { name: "Chaco" },
  { name: "Corrientes" },
  { name: "Santiago del Estero" },
  { name: "San Juan" },
  { name: "Jujuy" },
  { name: "Río Negro" },
  { name: "Neuquén" },
  { name: "Formosa" },
  { name: "Chubut" },
  { name: "San Luis" },
  { name: "Catamarca" },
  { name: "La Rioja" },
  { name: "La Pampa" },
  { name: "Santa Cruz" },
  { name: "Tierra del Fuego" },
];
