export const objectValues = {
    StepOne: {
      title: "",
      description: "",
      typeProp: "",
      amount: "",
      expenseAmount: "",
      postalCode: "",
      street: "",
      intersectionOne: "",
      intersectionTwo: "",
      pais: "",
      province: "",
      state: "",
      city: "",
      barrio: "",
      number: "",
      piso: "",
      depto: "",
      mapUbication: [],
    },
    StepTwo: {
      propertyStatus: "",
      ambient: "",
      bedroom: "",
      bathroom: "",
      surface: "",
      antiquity: "",
      generalAttributes: [],
      typesAmbients: [],
      services: [],
      plane: [],
      video: [],
      mainImage: "",
      multimedia: [],
    },
    StepThree: {
      disponibilidad: "",
      periodo: "",
      garantia: [],
      name: "",
      lastname: "",
      email: "",
      phone: "",
      location: "",
      documents: [],
      contratoExc: [],
    },
  };
  